services:
  eventstore:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=all
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"

  parking-registration:
    build: ./ParkingRegistration
    ports:
      - "80:80"
    networks:
      - local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - eventstore

  email-service:
    build: ./EmailService
    networks:
      - local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      
  sms-service:
    build: ./SmsService
    networks:
      - local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      
  event-service:
    build: ./EventService
    depends_on:
      - parking-registration
    networks:
      - local
      
  parking-control-service:
    build: ./ParkingControlService
    ports:
      - "8080:80"
    depends_on:
      - parking-registration
      - plate-recognizer-service
    networks:
      - local

  plate-recognizer-service:
    build: ./PlateRecognizerService
    depends_on:
      - parking-registration
    networks:
      - local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

networks:
  local:
    driver: bridge